#!/usr/bin/env bash
set -euo pipefail

# Deploys the relay service (relay/server.js) to a remote host over SSH.
# Intended for 阿里云效 (Alibaba Cloud DevOps) pipelines.
#
# Required env:
#   DEPLOY_HOST                Remote host/IP
#
# Optional SSH env:
#   DEPLOY_USER                Default: root
#   DEPLOY_PORT                Default: 22
#   DEPLOY_SSH_KEY_PATH        Path to private key file (preferred)
#   SSH_PRIVATE_KEY            Private key content (will be written to a temp file)
#   DEPLOY_SSH_OPTS            Extra ssh opts (space-separated)
#
# Optional deploy env:
#   DEPLOY_PATH                Default: /www/ticos-realtime-relay
#   DEPLOY_RELEASE_ID          Default: UTC timestamp (YYYYmmddHHMMSS)
#   DEPLOY_MODE                systemd (default) | nohup
#   DEPLOY_SERVICE_NAME        Default: ticos-realtime-relay
#   DEPLOY_NODE_BIN            Default: node (resolved via /usr/bin/env)
#   DEPLOY_SUDO                true (default for systemd) | false
#   DEPLOY_DISABLE_HOSTKEYCHECK true (default) | false
#   DEPLOY_ENV_MODE            if_missing (default) | keep | merge | overwrite
#
# Relay runtime env (written into shared/relay.env on the server):
#   PORT / RELAY_PORT, TARGET_URL, AUTH_TOKEN, AUTHORIZATION, ALLOW_DEBUG_TOKEN, LOG_LEVEL
#
# Notes:
# - SSH_PRIVATE_KEY / DEPLOY_SSH_KEY_PATH are for SSH auth to your server.
# - AUTH_TOKEN/AUTHORIZATION are for the relay to set an upstream Authorization header.

require() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Missing required env var: $name" >&2
    exit 2
  fi
}

DEPLOY_HOST="${DEPLOY_HOST:-}"
require DEPLOY_HOST

DEPLOY_USER="${DEPLOY_USER:-root}"
DEPLOY_PORT="${DEPLOY_PORT:-22}"
DEPLOY_PATH="${DEPLOY_PATH:-/www/ticos-realtime-relay}"
DEPLOY_SERVICE_NAME="${DEPLOY_SERVICE_NAME:-ticos-realtime-relay}"
DEPLOY_MODE="${DEPLOY_MODE:-systemd}"
DEPLOY_NODE_BIN="${DEPLOY_NODE_BIN:-node}"
DEPLOY_RELEASE_ID="${DEPLOY_RELEASE_ID:-$(date -u +"%Y%m%d%H%M%S")}"
DEPLOY_DISABLE_HOSTKEYCHECK="${DEPLOY_DISABLE_HOSTKEYCHECK:-true}"
DEPLOY_SSH_OPTS="${DEPLOY_SSH_OPTS:-}"
DEPLOY_ENV_MODE="${DEPLOY_ENV_MODE:-if_missing}"

if [[ "${DEPLOY_MODE}" != "systemd" && "${DEPLOY_MODE}" != "nohup" ]]; then
  echo "DEPLOY_MODE must be 'systemd' or 'nohup' (got: ${DEPLOY_MODE})" >&2
  exit 2
fi

if [[ "${DEPLOY_ENV_MODE}" != "if_missing" && "${DEPLOY_ENV_MODE}" != "keep" && "${DEPLOY_ENV_MODE}" != "merge" && "${DEPLOY_ENV_MODE}" != "overwrite" ]]; then
  echo "DEPLOY_ENV_MODE must be one of: if_missing | keep | merge | overwrite (got: ${DEPLOY_ENV_MODE})" >&2
  exit 2
fi

if [[ -z "${DEPLOY_SUDO:-}" ]]; then
  if [[ "${DEPLOY_USER}" == "root" ]]; then
    DEPLOY_SUDO="false"
  elif [[ "${DEPLOY_MODE}" == "systemd" ]]; then
    DEPLOY_SUDO="true"
  else
    DEPLOY_SUDO="false"
  fi
fi

ssh_opts_ssh=(-p "${DEPLOY_PORT}")
ssh_opts_scp=(-P "${DEPLOY_PORT}")
if [[ "${DEPLOY_DISABLE_HOSTKEYCHECK}" == "true" ]]; then
  ssh_opts_ssh+=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null)
  ssh_opts_scp+=(-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null)
fi

if [[ -n "${DEPLOY_SSH_OPTS}" ]]; then
  # shellcheck disable=SC2206
  ssh_opts_ssh+=(${DEPLOY_SSH_OPTS})
  # shellcheck disable=SC2206
  ssh_opts_scp+=(${DEPLOY_SSH_OPTS})
fi

cleanup_paths=()
cleanup() {
  for p in "${cleanup_paths[@]:-}"; do
    rm -f "${p}" 2>/dev/null || true
  done
}
trap cleanup EXIT

key_path="${DEPLOY_SSH_KEY_PATH:-${SSH_KEY:-}}"
if [[ -z "${key_path}" && -n "${SSH_PRIVATE_KEY:-}" ]]; then
  key_path="$(mktemp -t relay_deploy_key.XXXXXX)"
  cleanup_paths+=("${key_path}")
  umask 077
  printf '%s\n' "${SSH_PRIVATE_KEY}" >"${key_path}"
fi

if [[ -n "${key_path}" ]]; then
  key_path="${key_path/#\~/${HOME}}"
  ssh_opts_ssh+=(-i "${key_path}")
  ssh_opts_scp+=(-i "${key_path}")
fi

ssh_base=(ssh "${ssh_opts_ssh[@]}" "${DEPLOY_USER}@${DEPLOY_HOST}")
scp_base=(scp "${ssh_opts_scp[@]}")

if [[ ! -f "relay/server.js" || ! -f "relay/package.json" ]]; then
  echo "Expected relay files not found. Run from repo root (missing relay/server.js or relay/package.json)." >&2
  exit 2
fi

tmp_tgz="$(mktemp -t relay_bundle.XXXXXX.tgz)"
cleanup_paths+=("${tmp_tgz}")
tar -C relay -czf "${tmp_tgz}" server.js package.json

tmp_env=""
should_upload_env="false"
if [[ "${DEPLOY_ENV_MODE}" != "keep" ]]; then
  if [[ -n "${PORT:-}" || -n "${RELAY_PORT:-}" || -n "${TARGET_URL:-}" || -n "${AUTH_TOKEN:-}" || -n "${AUTHORIZATION:-}" || -n "${ALLOW_DEBUG_TOKEN:-}" || -n "${LOG_LEVEL:-}" ]]; then
    should_upload_env="true"
  fi
  if [[ "${DEPLOY_ENV_MODE}" == "merge" || "${DEPLOY_ENV_MODE}" == "overwrite" ]]; then
    should_upload_env="true"
  fi
fi

if [[ "${should_upload_env}" == "true" ]]; then
  tmp_env="$(mktemp -t relay_env.XXXXXX)"
  cleanup_paths+=("${tmp_env}")
  umask 077
  {
    echo "# Generated by aliyun_remote_deploy_relay.sh"
    [[ -n "${PORT:-}" ]] && echo "PORT=${PORT}"
    [[ -n "${RELAY_PORT:-}" ]] && echo "RELAY_PORT=${RELAY_PORT}"
    [[ -n "${TARGET_URL:-}" ]] && echo "TARGET_URL=${TARGET_URL}"
    [[ -n "${AUTH_TOKEN:-}" ]] && echo "AUTH_TOKEN=${AUTH_TOKEN}"
    [[ -n "${AUTHORIZATION:-}" ]] && echo "AUTHORIZATION=${AUTHORIZATION}"
    [[ -n "${ALLOW_DEBUG_TOKEN:-}" ]] && echo "ALLOW_DEBUG_TOKEN=${ALLOW_DEBUG_TOKEN}"
    [[ -n "${LOG_LEVEL:-}" ]] && echo "LOG_LEVEL=${LOG_LEVEL}"
  } >"${tmp_env}"
  chmod 600 "${tmp_env}"
fi

remote_tmp="/tmp/${DEPLOY_SERVICE_NAME}-${DEPLOY_RELEASE_ID}.tgz"
remote_tmp_env="/tmp/${DEPLOY_SERVICE_NAME}-${DEPLOY_RELEASE_ID}.env"

echo "Uploading bundle to ${DEPLOY_USER}@${DEPLOY_HOST}:${remote_tmp}"
"${scp_base[@]}" "${tmp_tgz}" "${DEPLOY_USER}@${DEPLOY_HOST}:${remote_tmp}"
if [[ "${should_upload_env}" == "true" ]]; then
  echo "Uploading env to ${DEPLOY_USER}@${DEPLOY_HOST}:${remote_tmp_env} (mode=${DEPLOY_ENV_MODE})"
  "${scp_base[@]}" "${tmp_env}" "${DEPLOY_USER}@${DEPLOY_HOST}:${remote_tmp_env}"
fi

use_sudo="false"
if [[ "${DEPLOY_SUDO}" == "true" ]]; then
  use_sudo="true"
fi

remote_release_dir="${DEPLOY_PATH}/releases/${DEPLOY_RELEASE_ID}"
remote_current_link="${DEPLOY_PATH}/current"
remote_shared_dir="${DEPLOY_PATH}/shared"
remote_env_file="${remote_shared_dir}/relay.env"

echo "Deploying release ${DEPLOY_RELEASE_ID} to ${DEPLOY_PATH} (${DEPLOY_MODE})"
"${ssh_base[@]}" bash -s -- \
  "${remote_tmp}" \
  "${remote_tmp_env}" \
  "${remote_release_dir}" \
  "${remote_current_link}" \
  "${remote_shared_dir}" \
  "${remote_env_file}" \
  "${DEPLOY_MODE}" \
  "${DEPLOY_SERVICE_NAME}" \
  "${DEPLOY_NODE_BIN}" \
  "${use_sudo}" \
  "${DEPLOY_ENV_MODE}" \
  "${should_upload_env}" <<'REMOTE'
set -euo pipefail

remote_tmp="$1"
remote_tmp_env="$2"
release_dir="$3"
current_link="$4"
shared_dir="$5"
env_file="$6"
mode="$7"
service_name="$8"
node_bin="$9"
use_sudo="${10}"
env_mode="${11}"
has_uploaded_env="${12}"

sudo_prefix=""
if [[ "${use_sudo}" == "true" ]]; then
  sudo_prefix="sudo -n"
fi

mkdir -p "$(dirname "${release_dir}")" "${shared_dir}"
mkdir -p "${release_dir}"
tar -xzf "${remote_tmp}" -C "${release_dir}"
rm -f "${remote_tmp}"

chmod 755 "${release_dir}"
ln -sfn "${release_dir}" "${current_link}"

umask 077
run_root() {
  if [[ -z "${sudo_prefix}" ]]; then
    bash -lc "$1"
  else
    ${sudo_prefix} bash -lc "$1"
  fi
}

ensure_env_file() {
  run_root ": >\"${env_file}\" && chmod 600 \"${env_file}\""
}

apply_env() {
  case "${env_mode}" in
    keep)
      [[ "${has_uploaded_env}" == "true" ]] && rm -f "${remote_tmp_env}" || true
      [[ -f "${env_file}" ]] || ensure_env_file
      ;;
    if_missing)
      if [[ -f "${env_file}" ]]; then
        [[ "${has_uploaded_env}" == "true" ]] && rm -f "${remote_tmp_env}" || true
        return 0
      fi
      if [[ "${has_uploaded_env}" == "true" ]]; then
        run_root "mv -f \"${remote_tmp_env}\" \"${env_file}\" && chmod 600 \"${env_file}\""
      else
        ensure_env_file
      fi
      ;;
    overwrite)
      if [[ "${has_uploaded_env}" != "true" ]]; then
        echo "DEPLOY_ENV_MODE=overwrite requires uploading env (set relay env vars or use DEPLOY_ENV_MODE=keep/if_missing)." >&2
        exit 3
      fi
      run_root "mv -f \"${remote_tmp_env}\" \"${env_file}\" && chmod 600 \"${env_file}\""
      ;;
    merge)
      if [[ "${has_uploaded_env}" != "true" ]]; then
        echo "DEPLOY_ENV_MODE=merge requires uploading env (set relay env vars or use DEPLOY_ENV_MODE=keep/if_missing)." >&2
        exit 3
      fi
      ensure_env_file
      run_root "tmp_in=\"${remote_tmp_env}\"; tmp_out=\"${env_file}.tmp.$$\"; cp \"${env_file}\" \"${tmp_out}\"; \
        while IFS= read -r line; do \
          [[ -z \"${line}\" || \"${line}\" == \\#* ]] && continue; \
          key=\"${line%%=*}\"; \
          [[ -z \"${key}\" ]] && continue; \
          grep -v \"^${key}=\" \"${tmp_out}\" > \"${tmp_out}.2\" || true; \
          mv -f \"${tmp_out}.2\" \"${tmp_out}\"; \
        done <\"${tmp_in}\"; \
        cat \"${tmp_in}\" >>\"${tmp_out}\"; \
        mv -f \"${tmp_out}\" \"${env_file}\"; \
        chmod 600 \"${env_file}\"; \
        rm -f \"${tmp_in}\""
      ;;
    *)
      echo "Unhandled DEPLOY_ENV_MODE: ${env_mode}" >&2
      exit 3
      ;;
  esac
}

apply_env

if [[ "${mode}" == "systemd" ]]; then
  unit_path="/etc/systemd/system/${service_name}.service"

  ${sudo_prefix} tee "${unit_path}" >/dev/null <<UNIT
[Unit]
Description=Ticos Realtime Relay
After=network.target

[Service]
Type=simple
WorkingDirectory=${current_link}
EnvironmentFile=-${env_file}
ExecStart=/usr/bin/env ${node_bin} ${current_link}/server.js
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
UNIT

  ${sudo_prefix} systemctl daemon-reload
  ${sudo_prefix} systemctl enable "${service_name}"
  ${sudo_prefix} systemctl restart "${service_name}"
  ${sudo_prefix} systemctl status "${service_name}" --no-pager -l || true
  exit 0
fi

pid_file="${shared_dir}/relay.pid"
log_file="${shared_dir}/relay.log"

if [[ -f "${pid_file}" ]]; then
  old_pid="$(cat "${pid_file}" || true)"
  if [[ -n "${old_pid}" ]] && kill -0 "${old_pid}" 2>/dev/null; then
    kill "${old_pid}" || true
    sleep 1
    kill -9 "${old_pid}" 2>/dev/null || true
  fi
fi

nohup bash -lc "set -a; source \"${env_file}\"; set +a; exec /usr/bin/env ${node_bin} \"${current_link}/server.js\"" \
  >>"${log_file}" 2>&1 &
echo $! >"${pid_file}"
echo "Started relay (pid=$(cat "${pid_file}")) log=${log_file}"
REMOTE

echo "Done."
